sudo : required
services:
  - docker
before_install:
  - docker build -t omer/docker-react -f Dockerfile.dev .

script :
  - docker run -e CI=true omer/docker-react npm run

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-309596618141"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure : $AWS_SECRET_KEY
